name: Create Linear Issues on Push to main

# TODO: change branch name to uat or staging
# TODO: trigger workflow on PR events

on:
  push:
    branches:
      - main

jobs:
  create-linear-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run create-linear-issues script
        run: |
          ./.github/scripts/create-linear-todos.sh
        env:
          LINEAR_API_KEY: ${{ secrets.LINEAR_API_KEY }}
          TEAM_ID: ${{ secrets.LINEAR_TEAM_ID }}
          GITHUB_BEFORE: ${{ github.event.before }}
          GITHUB_AFTER: ${{ github.event.after }}
          REPO_NAME: ${{ github.event.repository.full_name }}
